[package]
name = "ircayc"
version = "0.1.0"
authors = ["asocha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irc = "0.14"